_prefs: 
  mapid: ruben.8901686a
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -102.8618
  - 22.7759
  - 11
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 5
name: Mexico-inegi-red-vial-diff
source: "mapbox:///ruben.afe621a4,enf.y4dyrpb9"
styles: 
  - style.mss
template: ''
