_prefs: 
  mapid: ruben.edc1d722
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -99.1123
  - 19.3994
  - 14
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 10
name: Mexico-df-names
source: "mapbox:///ruben.3a555c60"
styles: 
  - style.mss
template: ''
