_prefs: 
  mapid: ruben.b23afb36
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -99.5677
  - 19.2851
  - 17
description: Mapa solo de la inegi
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 5
name: Map-inegi
source: "mapbox:///ruben.afe621a4"
styles: 
  - style.mss
template: ''
