_prefs: 
  mapid: ruben.dec700e8
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -99.1453
  - 19.3668
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 19
minzoom: 10
name: Mexico-df-diff-josm-id
source: "mapbox:///ruben.3a555c60,enf.y4dyrpb9"
styles: 
  - style.mss
template: ''
