_prefs: 
  mapid: ruben.8901686a
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -104.4031
  - 23.4683
  - 7
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 5
name: Mexico-inegi-red-vial-diff2
source: "mapbox:///ruben.afe621a4,enf.y4dyrpb9"
styles: 
  - style.mss
template: ''
