_prefs: 
  mapid: ruben.887e8261
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -97.7645
  - 21.5201
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 13
name: Mexico-inegi-red-vial-names
source: "mapbox:///ruben.afe621a4"
styles: 
  - style.mss
template: ''
