_prefs: 
  mapid: ruben.887e8261
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -97.8274
  - 21.5233
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 5
name: Mexico-inegi-red-vial-names
source: "mapbox:///ruben.2f8a4c6c"
styles: 
  - style.mss
template: ''
