_prefs: 
  mapid: ruben.409ded1c
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -101.0315
  - 22.285
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 5
name: Mexico-inegi-red-vial-diff
source: "mapbox:///ruben.2f8a4c6c,enf.y4dyrpb9"
styles: 
  - style.mss
template: ''
