_prefs: 
  mapid: ruben.e31004f7
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -99.1216
  - 19.426
  - 17
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 17
minzoom: 16
name: Mexico-df-osm-web(10-17)
source: "mapbox:///enf.y4dyrpb9"
styles: 
  - style.mss
template: ''
